# Generated by Django 4.2.6 on 2023-12-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_item_rename_category_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory_item',
            name='item_no',
        ),
    ]
