# Generated by Django 4.2.6 on 2023-12-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(blank=True, default='USD - United States Dollar', max_length=225, null=True),
        ),
    ]
